Name: omniread-backend
Log:
  Mode: console
  Level: debug
ListenOn: 0.0.0.0:8080
State: dev
Auth:
  SecretKey: "secret"
  PublicKey: "public"
  AccessExpire: 86400
WeApp:
  AppID: "appid"
  AppSecret: "secret"
Mongo:
  URL: "mongodb://localhost:27018"
  DB: "omniread"
Cache:
  - Host: "localhost:6376"
    Pass: "123456"
Redis:
  Host: "localhost:6376"
  Pass: "123456"
  Type: node
OSS:
  Endpoint: "127.0.0.1:9000"
  AccessKeyID: "minioadmin"
  SecretAccessKey: "minioadmin"
  BucketName: "omniread-books"
  UseSSL: false
Bocha:
  APIKey: "YOUR_BOCHA_API_KEY"
