Name: omniread-backend
Log:
  Mode: console
  Level: debug
ListenOn: 0.0.0.0:8080
State: dev
Auth:
  SecretKey: "YOUR_SECRET_KEY"
  PublicKey: "YOUR_PUBLIC_KEY"
  AccessExpire: 86400
WeApp:
  AppID: "YOUR_APP_ID"
  AppSecret: "YOUR_APP_SECRET"
Mongo:
  URL: "mongodb://localhost:27017"
  DB: "omniread"
Cache:
  - Host: "localhost:6379"
    Pass: "YOUR_REDIS_PASSWORD"
Redis:
  Host: "localhost:6379"
  Pass: "YOUR_REDIS_PASSWORD"
  Type: node
OSS:
  Endpoint: "127.0.0.1:9000"
  AccessKeyID: "YOUR_MINIO_ACCESS_KEY"
  SecretAccessKey: "YOUR_MINIO_SECRET_KEY"
  BucketName: "omniread-books"
  UseSSL: false
Bocha:
  APIKey: "YOUR_BOCHA_API_KEY"
